# Generated by Django 5.2.13 on 2026-04-13 12:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('cached_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
    ]
